### ISSUE TITLE
PyPI packaging and distribution?

### ISSUE THREAD

**Issue by elsiehupp** [dblume/email-feed#3]
I was able to figure out PyPI packaging and distribution [for `liblarch`](https://github.com/getting-things-gnome/liblarch/issues/24) (though none of the maintainers got around to setting up PyPI account to actually pull the trigger). Is this something you would be open to me helping you with?

(I ask because PyPI is just much more convenient than manually downloading or cloning for production use cases and dependency management.)

**Comment by dblume** [comment]
Thank you for the offer Elsie. This project is more of a stand-alone application/service than a Python module, I don't think it warrants an entry into PyPI. If I change my mind, I'll reach back out to you.
